#!/usr/bin/env bash

bspc rule -r "*"

### Colors {

color_background=$(xgetres background)
color_accent=$(xgetres color10) 

# }




### Autostart {

~/.config/autostart.sh &

# }




### Workspace / Monitor config {

# Divide desktops between connected monitors {
DESKTOPS_COUNT=10

MONITORS=$(xrandr --listactivemonitors | sed -n '1!p' | awk '{print $4}')
DESKTOPS_PER_MONITOR=$(expr $DESKTOPS_COUNT / $(echo $MONITORS | wc -w))

INDEX=0
for m in $MONITORS; do
  FIRST=$(expr $INDEX "*" $DESKTOPS_PER_MONITOR + 1)
  LAST=$(expr $(expr $INDEX "*" $DESKTOPS_PER_MONITOR) + $DESKTOPS_PER_MONITOR)
  bspc monitor $m -d $(seq $FIRST $LAST)
  let INDEX=INDEX+1
done
# }

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

# }




### UI config {

bspc config normal_border_color '#2b263a'
bspc config focused_border_color '#8585f5'
bspc config presel_feedback_color '#91a9ff'

# bspc config normal_border_color   $color_background
# bspc config focused_border_color  $color_accent
# bspc config active_border_color   $color_accent

bspc config border_width        3
bspc config window_gap          5

bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config pointer_follows_monitor   true
bspc config click_to_focus            any

bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true

# }




### Layouts config {

bspc config split_ratio          0.5

# }




### Node rules {

# }
